[package]
name = "p256-cortex-m4"
version = "0.1.0-pre"
authors = ["Nicolas Stalder <n@stalder.io>"]
edition = "2018"

[dependencies]
der = { version = "0.2.9", features = ["big-uint", "derive"], optional = true }
# p256 = { version = "0.8.0-pre", default-features = false, features = ["ecdsa-core", "zeroize"] }
p256-cortex-m4-sys = "0.1.0-alpha.1"
# p256-cortex-m4-sys = { path = "../p256-cortex-m4-sys" }
rand_core = { version = "0.5.1", default-features = false }
sha2 = { version = "0.9", default-features = false, optional = true }
zeroize = { version = "1.2.0", default-features = false, features = ["zeroize_derive"] }

[features]
default = []
der-signatures = ["der"]
prehash = ["sha2"]
